ArrayList<Estado> estado = new ArrayList<Estado>();

void WriteValores(){
estado.add(new Estado("ALAGOAS"));
estado.get(0).porto.add(new Porto("MACEIÓ"));
estado.add(new Estado("AMAPÁ"));
estado.get(1).porto.add(new Porto("CURUÁ"));
estado.get(1).porto.add(new Porto("SANTANA"));
estado.add(new Estado("BAHIA"));
estado.get(2).porto.add(new Porto("MADRE DE\nDEUS"));
estado.get(2).porto.add(new Porto("ILHÉUS"));
estado.get(2).porto.add(new Porto("ARATU"));
estado.get(2).porto.add(new Porto("SALVADOR"));
estado.add(new Estado("CEARÁ"));
estado.get(3).porto.add(new Porto("PECÉM"));
estado.get(3).porto.add(new Porto("MUCURIPE"));
estado.add(new Estado("ESPÍRITO\nSANTO"));
estado.get(4).porto.add(new Porto("TUBARÃO"));
estado.get(4).porto.add(new Porto("ILHA DA\nTRINDADE"));
estado.get(4).porto.add(new Porto("PONTA\nDO UBU"));
estado.get(4).porto.add(new Porto("BORRA DO\nRIACHO"));
estado.get(4).porto.add(new Porto("VITÓRIA"));
estado.add(new Estado("MARANHÃO"));
estado.get(5).porto.add(new Porto("PONTA DA\nMADEIRA"));
estado.get(5).porto.add(new Porto("TERMINAL\nDA ALUMAR"));
estado.get(5).porto.add(new Porto("SÃO LUIZ"));
estado.get(5).porto.add(new Porto("TUTÓIA"));
estado.get(5).porto.add(new Porto("ITAQUI"));
estado.add(new Estado("PARÁ"));
estado.get(6).porto.add(new Porto("ILHAS DOS\nGRARÁS"));
estado.get(6).porto.add(new Porto("SALINÓPOLIS"));
estado.get(6).porto.add(new Porto("VIDA DO\nCONDE"));
estado.get(6).porto.add(new Porto("BELÉM"));
estado.get(6).porto.add(new Porto("BREVES"));
estado.get(6).porto.add(new Porto("ILHA DO\nMOSQUEIRO"));
estado.add(new Estado("PARAÍBA"));
estado.get(7).porto.add(new Porto("CABEDELO"));
estado.add(new Estado("PARANÁ"));
estado.get(8).porto.add(new Porto("CANAL DA\nGALHETA"));
estado.get(8).porto.add(new Porto("PONTA DO\nFÉLIX"));
estado.get(8).porto.add(new Porto("CANAL\nSUESTE"));
estado.get(8).porto.add(new Porto("CAIS OESTE"));
estado.add(new Estado("PERNAMBUCO"));
estado.get(9).porto.add(new Porto("FERNANDO\nDE NORONHA"));
estado.get(9).porto.add(new Porto("REFICE"));
estado.get(9).porto.add(new Porto("SUAPE"));
estado.add(new Estado("PIAUÍ"));
estado.get(10).porto.add(new Porto("LUÍS\nCORREIA"));
estado.add(new Estado("RIO DE\nJANEIRO"));
estado.get(11).porto.add(new Porto("ITAGUAÍ"));
estado.get(11).porto.add(new Porto("ANGRA\nDOS REIS"));
estado.get(11).porto.add(new Porto("PORTO\nDO FORNO"));
estado.get(11).porto.add(new Porto("PORTO\nDO AÇU"));
estado.get(11).porto.add(new Porto("ILHA FISCAL"));
estado.get(11).porto.add(new Porto("ILHA GUAIBÁ"));
estado.get(11).porto.add(new Porto("TERMINAL\nIMBETIBA"));
estado.add(new Estado("RIO GRANDE\nDO NORTE"));
estado.get(12).porto.add(new Porto("AREIA\nBRANCA"));
estado.get(12).porto.add(new Porto("GUARAMÉ"));
estado.get(12).porto.add(new Porto("NATAL"));
estado.get(12).porto.add(new Porto("MACAU"));
estado.add(new Estado("RIO GRANDE\nDO SUL"));
estado.get(13).porto.add(new Porto("RIO GRANDE"));
estado.add(new Estado("SANTA\nCATARINA"));
estado.get(14).porto.add(new Porto("SÃO FRANC\nDO SUL"));
estado.get(14).porto.add(new Porto("ITAJAÍ"));
estado.get(14).porto.add(new Porto("IMBITUBA"));
estado.get(14).porto.add(new Porto("FLORIANÓP"));
estado.add(new Estado("SÃO PAULO"));
estado.get(15).porto.add(new Porto("SANTOS"));
estado.get(15).porto.add(new Porto("SÃO\nSEBASTIÃO"));
estado.add(new Estado("SERGIPE"));
estado.get(16).porto.add(new Porto("CAPITANIA\nDE SERGIPE"));
estado.get(16).porto.add(new Porto("INÁCIO\nBARBOSA"));
}
